name: metrics
version: 0.0.1-dev
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: Metrics provides a powerful toolkit of ways to measure the behavior of critical components in your production environment.
homepage: https://github.com/a14n/dart-metrics
dependencies:
  path: any
dev_dependencies:
  mock: any
  unittest: any
