name: metrics
version: 0.1.0-dev
description: Metrics provides a powerful toolkit of ways to measure the behavior of critical components in your production environment.
homepage: https://github.com/a14n/dart-metrics

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0
  logging: ^1.0.1

dev_dependencies:
  mocktail: ^0.1.4
  test: ^1.17.10
  lints: ^1.0.1
