name: metrics
version: 0.1.0-dev
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: Metrics provides a powerful toolkit of ways to measure the behavior of critical components in your production environment.
homepage: https://github.com/a14n/dart-metrics

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: '1.8.0'
  logging: '1.0.1'

dev_dependencies:
  mockito: any
  build_runner: any
  test: any
