name: metrics
version: 0.2.2
description: Metrics provides a powerful toolkit of ways to measure the behavior of critical components in your production environment.
homepage: https://github.com/a14n/dart-metrics

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  clock: ^1.1.0
  logging: ^1.0.1
  meta: ^1.7.0
  path: ^1.8.0

dev_dependencies:
  expector: ^0.1.3
  lints: ^1.0.1
  mocktail: ^0.1.4
  test: ^1.17.10
