name: metrics
version: 0.0.2+1
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: Metrics provides a powerful toolkit of ways to measure the behavior of critical components in your production environment.
homepage: https://github.com/a14n/dart-metrics
dependencies:
  path: '>=1.0.0 <2.0.0'
  logging: '>=0.9.0 <0.10.0'
dev_dependencies:
  mock: any
  unittest: any
